// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.CarMarketplace.Public.Dealers;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.CarMarketplace.Public.Dealers;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IDealerAppService), typeof(DealerClientProxy))]
public partial class DealerClientProxy : ClientProxyBase<IDealerAppService>, IDealerAppService
{
    public virtual async Task<DealerDto> FindByShortNameAsync(string shortName)
    {
        return await RequestAsync<DealerDto>(nameof(FindByShortNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), shortName }
        });
    }

    public virtual async Task<DealerDto> GetAsync(Guid id)
    {
        return await RequestAsync<DealerDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<DealerDto>> GetListAsync(GetDealersInput input)
    {
        return await RequestAsync<PagedResultDto<DealerDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetDealersInput), input }
        });
    }
}
