// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.CarMarketplace.Public.UsedCars;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.CarMarketplace.Public.UsedCars;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IUsedCarAppService), typeof(UsedCarClientProxy))]
public partial class UsedCarClientProxy : ClientProxyBase<IUsedCarAppService>, IUsedCarAppService
{
    public virtual async Task<List<String>> GetAllModelColorsAsync()
    {
        return await RequestAsync<List<String>>(nameof(GetAllModelColorsAsync));
    }

    public virtual async Task<List<String>> GetAllModelLevelsAsync()
    {
        return await RequestAsync<List<String>>(nameof(GetAllModelLevelsAsync));
    }

    public virtual async Task<UsedCarDto> GetAsync(Guid id)
    {
        return await RequestAsync<UsedCarDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<UsedCarDto>> GetListAsync(GetUsedCarsInput input)
    {
        return await RequestAsync<PagedResultDto<UsedCarDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetUsedCarsInput), input }
        });
    }
}
